.TH "vkst::opencl_buffer< TBUFFER >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::opencl_buffer< TBUFFER >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstOpenCLBuffer\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBbuffer_type\fP = \fBTBUFFER\fP"
.br
.ti -1c
.RI "\fBusing\fP \fBlock_type\fP = \fBTLOCKTYPE\fP"
.br
.ti -1c
.RI "\fBusing\fP \fBself_type\fP = \fBopencl_buffer\fP< \fBTVALUE\fP, \fBTLOCKTYPE\fP, \fBTLOCKTYPE\fP >"
.br
.ti -1c
.RI "\fBusing\fP \fBpointer\fP = \fBtypename\fP \fBTBUFFER::pointer\fP"
.br
.ti -1c
.RI "\fBusing\fP \fBreference\fP = \fBtypename\fP TBUFFER::reference"
.br
.ti -1c
.RI "\fBusing\fP \fBsize_type\fP = \fBtypename\fP \fBTBUFFER::size_type\fP"
.br
.ti -1c
.RI "\fBusing\fP \fBconst_pointer\fP = \fBtypename\fP \fBTBUFFER::const_pointer\fP"
.br
.ti -1c
.RI "\fBusing\fP \fBconst_reference\fP = \fBtypename\fP TBUFFER::const_reference"
.br
.in -1c
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBopencl_buffer\fP (\fBbuffer_type\fP &\fBbuffer\fP, \fBcl_context\fP \fBcontext\fP, \fBbool\fP \fBreadOnly\fP)"
.br
.ti -1c
.RI "\fBopencl_buffer\fP (\fBconst\fP \fBself_type\fP &\fBother\fP) \fBnoexcept\fP=\fBdelete\fP"
.br
.ti -1c
.RI "\fBself_type\fP & \fBoperator=\fP (\fBconst\fP \fBself_type\fP &)=\fBdelete\fP"
.br
.ti -1c
.RI "\fBself_type\fP & \fBoperator=\fP (\fBconst\fP \fBself_type\fP &) \fBvolatile\fP=\fBdelete\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBassign_to_gpu\fP (\fBcl_command_queue\fP queue, \fBbool\fP \fBwrite2Device\fP=\fBtrue\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBrequire\fP (\fBcl_command_queue\fP queue, \fBbool\fP \fBreadDevice\fP)"
.br
.ti -1c
.RI "\fBcl_mem\fP \fBoperator cl_mem\fP () \fBconst\fP"
.br
.in -1c
.SS "Geschützte Methoden"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcreate_internal_gpu_buffer\fP ()"
.br
.in -1c
.SS "Geschützte Attribute"

.in +1c
.ti -1c
.RI "\fBbuffer_type\fP & \fBm_refBuffer\fP"
.br
.ti -1c
.RI "\fBcl_context\fP \fBm_cContext\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_bReadOnly\fP"
.br
.ti -1c
.RI "\fBlock_type\fP \fBm_lock\fP"
.br
.ti -1c
.RI "\fBcl_mem\fP \fBm_clBuffer\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBtypename\fP \fBTBUFFER\fP>
.br
class vkst::opencl_buffer< TBUFFER >"
.PP
\fBTemplate-Parameter\fP
.RS 4
\fITVALUE\fP 
.br
\fITLOCKTYPE\fP 
.br
\fITALLOCATOR\fP 
.RE
.PP

.PP
Definiert in Zeile \fB21\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::buffer_type =  \fBTBUFFER\fP"

.PP
Definiert in Zeile \fB23\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::const_pointer =  \fBtypename\fP \fBTBUFFER::const_pointer\fP"

.PP
Definiert in Zeile \fB30\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::const_reference =  \fBtypename\fP TBUFFER::const_reference"

.PP
Definiert in Zeile \fB31\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::lock_type =  \fBTLOCKTYPE\fP"

.PP
Definiert in Zeile \fB24\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::pointer =  \fBtypename\fP \fBTBUFFER::pointer\fP"

.PP
Definiert in Zeile \fB27\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::reference =  \fBtypename\fP TBUFFER::reference"

.PP
Definiert in Zeile \fB28\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::self_type =  \fBopencl_buffer\fP<\fBTVALUE\fP,\fBTLOCKTYPE\fP,\fBTLOCKTYPE\fP>"

.PP
Definiert in Zeile \fB25\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBusing\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::size_type =  \fBtypename\fP \fBTBUFFER::size_type\fP"

.PP
Definiert in Zeile \fB29\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SH "Beschreibung der Konstruktoren und Destruktoren"
.PP 
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::opencl_buffer (\fBbuffer_type\fP & buffer, \fBcl_context\fP context, \fBbool\fP readOnly)\fC [inline]\fP"

.PP
Definiert in Zeile \fB33\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::opencl_buffer (\fBconst\fP \fBself_type\fP & other)\fC [delete]\fP, \fC [noexcept]\fP"

.SH "Dokumentation der Elementfunktionen"
.PP 
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBbool\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::assign_to_gpu (\fBcl_command_queue\fP queue, \fBbool\fP write2Device = \fC\fBtrue\fP\fP)\fC [inline]\fP"

.PP
Definiert in Zeile \fB42\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBvirtual\fP \fBvoid\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::create_internal_gpu_buffer ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Definiert in Zeile \fB77\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBcl_mem\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >\fB::operator\fP \fBcl_mem\fP () const\fC [inline]\fP"

.PP
Definiert in Zeile \fB74\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBself_type\fP & \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >\fB::operator\fP= (\fBconst\fP \fBself_type\fP &) volatile\fC [delete]\fP"

.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBself_type\fP & \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >\fB::operator\fP= (\fBconst\fP \fBself_type\fP &)\fC [delete]\fP"

.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBbool\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::require (\fBcl_command_queue\fP queue, \fBbool\fP readDevice)\fC [inline]\fP"

.PP
Definiert in Zeile \fB57\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SH "Dokumentation der Felder"
.PP 
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBbool\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::m_bReadOnly\fC [protected]\fP"

.PP
Definiert in Zeile \fB87\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBcl_context\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::m_cContext\fC [protected]\fP"

.PP
Definiert in Zeile \fB86\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBcl_mem\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::m_clBuffer\fC [protected]\fP"

.PP
Definiert in Zeile \fB89\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBlock_type\fP \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::m_lock\fC [protected]\fP"

.PP
Definiert in Zeile \fB88\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTBUFFER\fP > \fBbuffer_type\fP& \fBvkst::opencl_buffer\fP< \fBTBUFFER\fP >::m_refBuffer\fC [protected]\fP"

.PP
Definiert in Zeile \fB85\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
