.TH "vkst::internal::type_with_alignment< 8 >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::type_with_alignment< 8 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Datenfelder"

.in +1c
.ti -1c
.RI "aligned8 \fBtype\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile \fB90\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Felder"
.PP 
.SS "aligned8 \fBvkst::internal::type_with_alignment\fP< 8 >::type"

.PP
Definiert in Zeile \fB90\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
