.TH "include/vkstAllocator.hpp" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vkstAllocator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br
\fC#include 'Allocator/vkstAllocatorBase\&.hpp'\fP
.br
\fC#include 'Allocator/vkstMallocAllocator\&.hpp'\fP
.br
\fC#include 'Allocator/vkstAllocatorMaximalFilter\&.hpp'\fP
.br

.SS "Namensbereiche"

.in +1c
.ti -1c
.RI "namespace \fBvkst\fP"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBvkst::default_allocator\fP = \fBmalloc_allocator\fP< \fBbasic_allocator_maximal_filter\fP< \fBLIBVKST_CONFIG_MAX_MEMORY_USE\fP > >"
.br
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
