.TH "vkst::alignment_of< T >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::alignment_of< T > \- A template to get the alignment of a type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "enum { \fBres\fP = offsetof(internal::alignof_helper<T>, y) }"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<typename T>
.br
struct vkst::alignment_of< T >"A template to get the alignment of a type\&. 

This template provides the alignment of any type \fCT\fP\&. It uses the \fCalignof_helper\fP structure to calculate the offset of the \fCy\fP member, which is aligned according to the alignment of \fCT\fP\&.
.PP
\fBTemplate-Parameter\fP
.RS 4
\fIT\fP The type to get the alignment for\&. 
.RE
.PP

.PP
Definiert in Zeile \fB143\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Aufzählungstypen"
.PP 
.SS "template<typename T > anonymous enum"

.PP
\fBAufzählungswerte\fP
.in +1c
.TP
\fB\fIres \fP\fP
.PP
Definiert in Zeile \fB144\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
