.TH "vkst::internal::max_align" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::max_align \- A union type to determine the maximum alignment\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Datenfelder"

.in +1c
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "short \fBs\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "long \fBl\fP"
.br
.ti -1c
.RI "long long \fBll\fP"
.br
.ti -1c
.RI "float \fBf\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
A union type to determine the maximum alignment\&. 

This union contains different types with varying alignment requirements\&. It allows us to compute the largest alignment required for any of these types\&. 
.PP
Definiert in Zeile \fB101\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Felder"
.PP 
.SS "char vkst::internal::max_align::c"

.PP
Definiert in Zeile \fB102\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "double vkst::internal::max_align::d"

.PP
Definiert in Zeile \fB108\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "float vkst::internal::max_align::f"

.PP
Definiert in Zeile \fB107\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "int vkst::internal::max_align::i"

.PP
Definiert in Zeile \fB104\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "long vkst::internal::max_align::l"

.PP
Definiert in Zeile \fB105\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "long long vkst::internal::max_align::ll"

.PP
Definiert in Zeile \fB106\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "short vkst::internal::max_align::s"

.PP
Definiert in Zeile \fB103\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
