.TH "vkst::aligned_as< T >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::aligned_as< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBres\fP = \fBtypename\fP \fBinternal::type_with_alignment\fP< \fBalignment_of\fP< T >::res >"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBtypename\fP T>
.br
struct vkst::aligned_as< T >"
.PP
Definiert in Zeile \fB129\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<\fBtypename\fP T > \fBusing\fP \fBvkst::aligned_as\fP< T >::res =  \fBtypename\fP \fBinternal::type_with_alignment\fP<\fBalignment_of\fP<T>::res>"

.PP
Definiert in Zeile \fB130\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
