.TH "vkst::is_thread_safe_allocator< TAlloC >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::is_thread_safe_allocator< TAlloC > \- Checks whether a given allocator is thread-safe\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAllocatorTraits\&.hpp>\fP
.PP
Abgeleitet von std::integral_constant< bool, internal::allocator_traits< TAlloC >::is_thread_safe::value >\&.
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<class TAlloC>
.br
struct vkst::is_thread_safe_allocator< TAlloC >"Checks whether a given allocator is thread-safe\&. 

This \fCintegral_constant\fP evaluates whether the allocator is thread-safe based on the allocator's traits\&.
.PP
\fBTemplate-Parameter\fP
.RS 4
\fITAlloC\fP The allocator type\&. 
.RE
.PP

.PP
Definiert in Zeile \fB50\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
