.TH "vkst::alignment_of< T >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::alignment_of< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "enum { \fBres\fP = offsetof(internal::alignof_helper<T>, y) }"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBtypename\fP T>
.br
struct vkst::alignment_of< T >"
.PP
Definiert in Zeile \fB80\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Aufzählungstypen"
.PP 
.SS "template<\fBtypename\fP T > \fBanonymous\fP \fBenum\fP"

.PP
\fBAufzählungswerte\fP
.in +1c
.TP
\fB\fIres \fP\fP
.PP
Definiert in Zeile \fB81\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
