.TH "vkst::is_pod< T >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::is_pod< T > \- A type trait to check if a type is a Plain Old Data (POD) type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.PP
Abgeleitet von std::integral_constant< bool, __is_pod(T)>\&.
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<typename T>
.br
struct vkst::is_pod< T >"A type trait to check if a type is a Plain Old Data (POD) type\&. 

This struct is used to check whether a type \fCT\fP is a POD type, which is a type that can be trivially copied or assigned without requiring a constructor, destructor, or copy assignment operator\&.
.PP
\fBTemplate-Parameter\fP
.RS 4
\fIT\fP The type to check\&. 
.RE
.PP

.PP
Definiert in Zeile \fB122\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
