.TH "vkst::internal::allocator_traits< TAlloC >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::allocator_traits< TAlloC > \- Traits for a given allocator type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAllocatorTraits\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "using \fBallocator_type\fP = TAlloC"
.br
.ti -1c
.RI "using \fBvalue_type\fP = typename allocator_type::value_type"
.br
.ti -1c
.RI "using \fBpointer\fP = typename allocator_type::pointer"
.br
.ti -1c
.RI "using \fBconst_pointer\fP = typename allocator_type::const_pointer"
.br
.ti -1c
.RI "using \fBdifference_type\fP = typename allocator_type::difference_type"
.br
.ti -1c
.RI "using \fBsize_type\fP = typename allocator_type::size_type"
.br
.ti -1c
.RI "using \fBallocator_category\fP = typename TAlloC::allocator_category"
.br
.ti -1c
.RI "using \fBis_thread_safe\fP = typename TAlloC::is_thread_safe"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<typename TAlloC>
.br
struct vkst::internal::allocator_traits< TAlloC >"Traits for a given allocator type\&. 

The \fC\fBallocator_traits\fP\fP struct provides type definitions and constants for different allocator types, such as \fCpointer\fP, \fCconst_pointer\fP, \fCdifference_type\fP, and others\&. It is used to query the properties of the allocator, such as the \fCallocator_category\fP and whether the allocator is thread-safe\&.
.PP
\fBTemplate-Parameter\fP
.RS 4
\fITAlloC\fP The allocator type to query the traits for\&. 
.RE
.PP

.PP
Definiert in Zeile \fB27\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::allocator_category =  typename TAlloC::allocator_category"

.PP
Definiert in Zeile \fB36\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::allocator_type =  TAlloC"

.PP
Definiert in Zeile \fB28\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::const_pointer =  typename allocator_type::const_pointer"

.PP
Definiert in Zeile \fB31\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::difference_type =  typename allocator_type::difference_type"

.PP
Definiert in Zeile \fB32\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::is_thread_safe =  typename TAlloC::is_thread_safe"

.PP
Definiert in Zeile \fB37\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::pointer =  typename allocator_type::pointer"

.PP
Definiert in Zeile \fB30\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::size_type =  typename allocator_type::size_type"

.PP
Definiert in Zeile \fB33\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<typename TAlloC > using \fBvkst::internal::allocator_traits\fP< TAlloC >::value_type =  typename allocator_type::value_type"

.PP
Definiert in Zeile \fB29\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
