.TH "vkst::short_alignment< Target, false >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::short_alignment< Target, false >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "using \fBtype\fP = typename \fBint_alignment\fP< Target, \fBalignment_of\fP< int >::res >=Target >::type"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<size_t Target>
.br
struct vkst::short_alignment< Target, false >"
.PP
Definiert in Zeile \fB192\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<size_t Target> using \fBvkst::short_alignment\fP< Target, false >::type =  typename \fBint_alignment\fP<Target, \fBalignment_of\fP<int>::res >= Target>::type"

.PP
Definiert in Zeile \fB193\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
