.TH "vkst::internal::type_with_alignment< N >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::type_with_alignment< N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBchar\fP \fBerr_invalid_alignment\fP[\fBN\fP > 0 ? \-1 :1]"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBsize_t\fP N>
.br
struct vkst::internal::type_with_alignment< N >"
.PP
Definiert in Zeile \fB43\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<\fBsize_t\fP N> \fBtypedef\fP \fBchar\fP \fBvkst::internal::type_with_alignment\fP< \fBN\fP >::err_invalid_alignment[\fBN\fP > 0 ? \-1 :1]"

.PP
Definiert in Zeile \fB44\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
