.TH "vkst::internal::type_with_alignment< 2 >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::type_with_alignment< 2 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Datenfelder"

.in +1c
.ti -1c
.RI "\fBaligned2\fP \fBtype\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile \fB48\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Felder"
.PP 
.SS "\fBaligned2\fP \fBvkst::internal::type_with_alignment\fP< 2 >::type"

.PP
Definiert in Zeile \fB48\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
