.TH "vkst::internal::allocator_traits< TAlloC >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::allocator_traits< TAlloC >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAllocatorTraits\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBallocator_type\fP = \fBTAlloC\fP"
.br
.ti -1c
.RI "\fBusing\fP \fBvalue_type\fP = \fBtypename\fP allocator_type::value_type"
.br
.ti -1c
.RI "\fBusing\fP \fBpointer\fP = \fBtypename\fP allocator_type::pointer"
.br
.ti -1c
.RI "\fBusing\fP \fBconst_pointer\fP = \fBtypename\fP allocator_type::const_pointer"
.br
.ti -1c
.RI "\fBusing\fP \fBdifference_type\fP = \fBtypename\fP allocator_type::difference_type"
.br
.ti -1c
.RI "\fBusing\fP \fBsize_type\fP = \fBtypename\fP allocator_type::size_type"
.br
.ti -1c
.RI "\fBusing\fP \fBallocator_category\fP = \fBtypename\fP TAlloC::allocator_category"
.br
.ti -1c
.RI "\fBusing\fP \fBis_thread_safe\fP = \fBtypename\fP TAlloC::is_thread_safe"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBtypename\fP \fBTAlloC\fP>
.br
struct vkst::internal::allocator_traits< TAlloC >"
.PP
Definiert in Zeile \fB17\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::allocator_category =  \fBtypename\fP TAlloC::allocator_category"

.PP
Definiert in Zeile \fB26\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::allocator_type =  \fBTAlloC\fP"

.PP
Definiert in Zeile \fB18\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::const_pointer =  \fBtypename\fP allocator_type::const_pointer"

.PP
Definiert in Zeile \fB21\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::difference_type =  \fBtypename\fP allocator_type::difference_type"

.PP
Definiert in Zeile \fB22\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::is_thread_safe =  \fBtypename\fP TAlloC::is_thread_safe"

.PP
Definiert in Zeile \fB27\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::pointer =  \fBtypename\fP allocator_type::pointer"

.PP
Definiert in Zeile \fB20\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::size_type =  \fBtypename\fP allocator_type::size_type"

.PP
Definiert in Zeile \fB23\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.
.SS "template<\fBtypename\fP \fBTAlloC\fP > \fBusing\fP \fBvkst::internal::allocator_traits\fP< \fBTAlloC\fP >::value_type =  \fBtypename\fP allocator_type::value_type"

.PP
Definiert in Zeile \fB19\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
