.TH "vkst::internal" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal
.SH SYNOPSIS
.br
.PP
.SS "Datenstrukturen"

.in +1c
.ti -1c
.RI "struct \fBalignof_helper\fP"
.br
.ti -1c
.RI "struct \fBallocator_traits\fP"
.br
.ti -1c
.RI "union \fBmax_align\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 1 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 16 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 2 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 32 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 4 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 64 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 8 >\fP"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "\fBstruct\fP \fB__attribute__\fP ((\fBaligned\fP(1))) \fBaligned1\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fB__attribute__\fP ((\fBaligned\fP(2))) \fBaligned2\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fB__attribute__\fP ((\fBaligned\fP(4))) \fBaligned4\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fB__attribute__\fP ((\fBaligned\fP(8))) \fBaligned8\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fB__attribute__\fP ((\fBaligned\fP(16))) \fBaligned16\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fB__attribute__\fP ((\fBaligned\fP(32))) \fBaligned32\fP"
.br
.ti -1c
.RI "\fBstruct\fP \fB__attribute__\fP ((\fBaligned\fP(64))) \fBaligned64\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBlevel2string\fP (\fBconst\fP \fBlogging_level\fP \fBlevel\fP)"
.br
.in -1c
.SH "Dokumentation der Funktionen"
.PP 
.SS "\fBstruct\fP vkst::internal::__attribute__ ((\fBaligned\fP(1)))"

.PP
Definiert in Zeile \fB175\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBstruct\fP vkst::internal::__attribute__ ((\fBaligned\fP(16)))"

.PP
Definiert in Zeile \fB175\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBstruct\fP vkst::internal::__attribute__ ((\fBaligned\fP(2)))"

.PP
Definiert in Zeile \fB175\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBstruct\fP vkst::internal::__attribute__ ((\fBaligned\fP(32)))"

.PP
Definiert in Zeile \fB175\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBstruct\fP vkst::internal::__attribute__ ((\fBaligned\fP(4)))"

.PP
Definiert in Zeile \fB175\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBstruct\fP vkst::internal::__attribute__ ((\fBaligned\fP(64)))"

.PP
Definiert in Zeile \fB175\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBstruct\fP vkst::internal::__attribute__ ((\fBaligned\fP(8)))"

.PP
Definiert in Zeile \fB175\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBconst\fP \fBchar\fP * vkst::internal::level2string (\fBconst\fP \fBlogging_level\fP level)\fC [inline]\fP"

.PP
Definiert in Zeile \fB28\fP der Datei \fBvkstLogging\&.hpp\fP\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
