.TH "vkst::alignment_of< void volatile >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::alignment_of< void volatile >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "enum { \fBres\fP = 0 }"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile \fB158\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Aufzählungstypen"
.PP 
.SS "anonymous enum"

.PP
\fBAufzählungswerte\fP
.in +1c
.TP
\fB\fIres \fP\fP
.PP
Definiert in Zeile \fB159\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
