.TH "vkst::char_alignment< Target, check >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::char_alignment< Target, check >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "using \fBtype\fP = char"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<size_t Target, bool check>
.br
struct vkst::char_alignment< Target, check >"
.PP
Definiert in Zeile \fB195\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<size_t Target, bool check> using \fBvkst::char_alignment\fP< Target, check >::type =  char"

.PP
Definiert in Zeile \fB195\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
