.TH "include/vkstAllocator.hpp" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vkstAllocator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Allocator/vkstMallocAllocator\&.hpp'\fP
.br
\fC#include 'Allocator/vkstAllocatorMaximalFilter\&.hpp'\fP
.br

.SS "Namensbereiche"

.in +1c
.ti -1c
.RI "namespace \fBvkst\fP"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "using \fBvkst::default_allocator\fP = \fBmalloc_allocator\fP< \fBbasic_allocator_filter\fP >"
.br
.RI "A default allocator that uses the malloc_allocator with a basic memory filter\&. "
.ti -1c
.RI "template<size_t TMaxAlloc> using \fBvkst::default_limmeted_allocator\fP = \fBmalloc_allocator\fP< \fBbasic_allocator_maximal_filter\fP< TMaxAlloc > >"
.br
.RI "A default allocator with a maximum allocation size limit\&. "
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
