.TH "include/vkstOpenCLBuffer.hpp" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vkstOpenCLBuffer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <CL/cl\&.h>\fP
.br
\fC#include <atomic>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <vkstBuffer\&.hpp>\fP
.br

.SS "Datenstrukturen"

.in +1c
.ti -1c
.RI "class \fBvkst::opencl_buffer< TBUFFER >\fP"
.br
.in -1c
.SS "Namensbereiche"

.in +1c
.ti -1c
.RI "namespace \fBvkst\fP"
.br
.in -1c
.SS "Makrodefinitionen"

.in +1c
.ti -1c
.RI "#define \fBCL_TARGET_OPENCL_VERSION\fP   300"
.br
.in -1c
.SH "Makro-Dokumentation"
.PP 
.SS "#define CL_TARGET_OPENCL_VERSION   300"

.PP
Definiert in Zeile \fB4\fP der Datei \fBvkstOpenCLBuffer\&.hpp\fP\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
