.TH "vkst::aligned_as< T >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::aligned_as< T > \- A helper type alias to align a type to its appropriate alignment\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "using \fBres\fP = typename \fBinternal::type_with_alignment\fP< \fBalignment_of\fP< T >::res >"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<typename T>
.br
struct vkst::aligned_as< T >"A helper type alias to align a type to its appropriate alignment\&. 

This alias ensures that the type \fCT\fP is aligned correctly according to its \fC\fBalignment_of\fP\fP\&.
.PP
\fBTemplate-Parameter\fP
.RS 4
\fIT\fP The type to align\&. 
.RE
.PP

.PP
Definiert in Zeile \fB207\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<typename T > using \fBvkst::aligned_as\fP< T >::res =  typename \fBinternal::type_with_alignment\fP<\fBalignment_of\fP<T>::res>"

.PP
Definiert in Zeile \fB208\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
