.TH "vkst::is_pod< T >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::is_pod< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.PP
Abgeleitet von std::integral_constant< bool, __is_pod(T)>\&.
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBtypename\fP T>
.br
struct vkst::is_pod< T >"
.PP
Definiert in Zeile \fB67\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
