.TH "vkst::internal" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal
.SH SYNOPSIS
.br
.PP
.SS "Datenstrukturen"

.in +1c
.ti -1c
.RI "struct \fBalignof_helper\fP"
.br
.RI "A helper structure for computing alignment of a given type\&. "
.ti -1c
.RI "struct \fBallocator_traits\fP"
.br
.RI "Traits for a given allocator type\&. "
.ti -1c
.RI "union \fBmax_align\fP"
.br
.RI "A union type to determine the maximum alignment\&. "
.ti -1c
.RI "struct \fBtype_with_alignment\fP"
.br
.RI "A template to enforce alignment for specific sizes\&. "
.ti -1c
.RI "struct \fBtype_with_alignment< 1 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 16 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 2 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 32 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 4 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 64 >\fP"
.br
.ti -1c
.RI "struct \fBtype_with_alignment< 8 >\fP"
.br
.in -1c
.SS "Funktionen"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((aligned(1))) aligned1"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((aligned(2))) aligned2"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((aligned(4))) aligned4"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((aligned(8))) aligned8"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((aligned(16))) aligned16"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((aligned(32))) aligned32"
.br
.ti -1c
.RI "struct \fB__attribute__\fP ((aligned(64))) aligned64"
.br
.ti -1c
.RI "const char * \fBlevel2string\fP (const \fBlogging_level\fP level)"
.br
.RI "Converts a logging level enum to a human-readable string\&. "
.in -1c
.SH "Dokumentation der Funktionen"
.PP 
.SS "struct vkst::internal::__attribute__ ((aligned(1)))"

.PP
Definiert in Zeile \fB315\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "struct vkst::internal::__attribute__ ((aligned(16)))"

.PP
Definiert in Zeile \fB315\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "struct vkst::internal::__attribute__ ((aligned(2)))"

.PP
Definiert in Zeile \fB315\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "struct vkst::internal::__attribute__ ((aligned(32)))"

.PP
Definiert in Zeile \fB315\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "struct vkst::internal::__attribute__ ((aligned(4)))"

.PP
Definiert in Zeile \fB315\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "struct vkst::internal::__attribute__ ((aligned(64)))"

.PP
Definiert in Zeile \fB315\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "struct vkst::internal::__attribute__ ((aligned(8)))"

.PP
Definiert in Zeile \fB315\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "const char * vkst::internal::level2string (const \fBlogging_level\fP level)\fC [inline]\fP"

.PP
Converts a logging level enum to a human-readable string\&. 
.PP
\fBParameter\fP
.RS 4
\fIlevel\fP The logging level to convert\&. 
.RE
.PP
\fBRückgabe\fP
.RS 4
A string representation of the logging level\&. 
.RE
.PP
< Default in case of an unknown level\&.
.PP
Definiert in Zeile \fB49\fP der Datei \fBvkstLogging\&.hpp\fP\&.
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
