.TH "vkst::internal::alignof_helper< T >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::alignof_helper< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Datenfelder"

.in +1c
.ti -1c
.RI "\fBchar\fP \fBx\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBtypename\fP T>
.br
struct vkst::internal::alignof_helper< T >"
.PP
Definiert in Zeile \fB28\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Felder"
.PP 
.SS "template<\fBtypename\fP T > \fBchar\fP \fBvkst::internal::alignof_helper\fP< T >::x"

.PP
Definiert in Zeile \fB29\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "template<\fBtypename\fP T > T \fBvkst::internal::alignof_helper\fP< T >::y"

.PP
Definiert in Zeile \fB30\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
