.TH "vkst::nodeleter_allocator_tag" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::nodeleter_allocator_tag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAllocatorTraits\&.hpp>\fP
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile \fB12\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
