.TH "vkst::long_double_alignment< Target, check >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::long_double_alignment< Target, check > \- Adjusts the alignment of a type based on the target alignment\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "using \fBtype\fP = long double"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<size_t Target, bool check>
.br
struct vkst::long_double_alignment< Target, check >"Adjusts the alignment of a type based on the target alignment\&. 

This set of templates ensures that a type's alignment satisfies the specified target alignment\&. It will fallback to types with larger alignments if necessary\&.
.PP
\fBTemplate-Parameter\fP
.RS 4
\fITarget\fP The target alignment\&. 
.br
\fIcheck\fP A boolean value used to check if the alignment of a type is sufficient\&. 
.RE
.PP

.PP
Definiert in Zeile \fB171\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<size_t Target, bool check> using \fBvkst::long_double_alignment\fP< Target, check >::type =  long double"

.PP
Definiert in Zeile \fB171\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
