.TH "vkst::internal::max_align" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::internal::max_align
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Datenfelder"

.in +1c
.ti -1c
.RI "\fBchar\fP \fBc\fP"
.br
.ti -1c
.RI "\fBshort\fP \fBs\fP"
.br
.ti -1c
.RI "\fBint\fP \fBi\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBl\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBlong\fP \fBll\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBf\fP"
.br
.ti -1c
.RI "\fBdouble\fP \fBd\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile \fB55\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der Felder"
.PP 
.SS "\fBchar\fP vkst::internal::max_align::c"

.PP
Definiert in Zeile \fB56\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBdouble\fP vkst::internal::max_align::d"

.PP
Definiert in Zeile \fB62\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBfloat\fP vkst::internal::max_align::f"

.PP
Definiert in Zeile \fB61\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBint\fP vkst::internal::max_align::i"

.PP
Definiert in Zeile \fB58\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBlong\fP vkst::internal::max_align::l"

.PP
Definiert in Zeile \fB59\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBlong\fP \fBlong\fP vkst::internal::max_align::ll"

.PP
Definiert in Zeile \fB60\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SS "\fBshort\fP vkst::internal::max_align::s"

.PP
Definiert in Zeile \fB57\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
