.TH "vkst::is_thread_safe_allocator< TAlloC >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::is_thread_safe_allocator< TAlloC >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAllocatorTraits\&.hpp>\fP
.PP
Abgeleitet von std::integral_constant< bool, internal::allocator_traits< TAlloC >::is_thread_safe::value >\&.
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBclass\fP \fBTAlloC\fP>
.br
struct vkst::is_thread_safe_allocator< TAlloC >"
.PP
Definiert in Zeile \fB31\fP der Datei \fBvkstAllocatorTraits\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
