.TH "include/Allocator/vkstMallocAllocator.hpp" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Allocator/vkstMallocAllocator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'vkstAllocatorTraits\&.hpp'\fP
.br

.SS "Datenstrukturen"

.in +1c
.ti -1c
.RI "class \fBvkst::basic_malloc_allocator\fP"
.br
.in -1c
.SS "Namensbereiche"

.in +1c
.ti -1c
.RI "namespace \fBvkst\fP"
.br
.in -1c
.SS "Typdefinitionen"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBTFilter\fP > \fBusing\fP \fBvkst::malloc_allocator\fP = \fBbasic_allocator\fP< \fBbasic_malloc_allocator\fP, \fBTFilter\fP >"
.br
.in -1c
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
