.TH "vkst::is_pod< internal::aligned8 >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::is_pod< internal::aligned8 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.PP
Abgeleitet von std::true_type\&.
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile \fB128\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
