.TH "vkst::double_alignment< Target, false >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::double_alignment< Target, false >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = \fBtypename\fP \fBlong_double_alignment\fP< \fBTarget\fP, \fBalignment_of\fP< \fBlong\fP \fBdouble\fP >::res >=\fBTarget\fP >::type"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBsize_t\fP Target>
.br
struct vkst::double_alignment< Target, false >"
.PP
Definiert in Zeile \fB105\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<\fBsize_t\fP Target> \fBusing\fP \fBvkst::double_alignment\fP< \fBTarget\fP, \fBfalse\fP >::type =  \fBtypename\fP \fBlong_double_alignment\fP<\fBTarget\fP, \fBalignment_of\fP<\fBlong\fP \fBdouble\fP>::res >= \fBTarget\fP>::type"

.PP
Definiert in Zeile \fB106\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
