.TH "vkst::double_alignment< Target, check >" 3 "vkbst" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vkst::double_alignment< Target, check >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vkstAlignment\&.hpp>\fP
.SS "Öffentliche Typen"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = \fBdouble\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 

.SS "template<\fBsize_t\fP Target, \fBbool\fP check>
.br
struct vkst::double_alignment< Target, check >"
.PP
Definiert in Zeile \fB104\fP der Datei \fBvkstAlignment\&.hpp\fP\&.
.SH "Dokumentation der benutzerdefinierten Datentypen"
.PP 
.SS "template<\fBsize_t\fP Target, \fBbool\fP check> \fBusing\fP \fBvkst::double_alignment\fP< \fBTarget\fP, \fBcheck\fP >::type =  \fBdouble\fP"

.PP
Definiert in Zeile \fB104\fP der Datei \fBvkstAlignment\&.hpp\fP\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für vkbst aus dem Quellcode\&.
